name: kairoz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  flutter_dotenv: ^5.1.0
  flutter_speed_dial: ^7.0.0
  http: ^1.2.2
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.1.0
  flutter_svg: ^2.0.14
  google_nav_bar: ^5.0.7
  syncfusion_flutter_calendar: ^27.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/fundo1.jpg
    - assets/estudos.png
    - assets/feynman.png
    - assets/pareto.jpg
    - assets/intercalado.jpg
    - .env
